apiVersion: apps/v1
kind: Deployment
metadata:
  name: april-tag-deployment
spec:
  selector:
    matchLabels:
      app: apriltag-localisation
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: apriltag-localisation
    spec:
      containers:
      - name: apriltag-localisation
        volumeMounts:
          - mountPath: /dev/video0
            name: dev-video0
        securityContext:
          privileged: true
        image: sid220/apriltag_localisation:latest
        ports:
        - containerPort: 80
        env:
          - name: DAPRILTAG_PRODUCTION
            value: "1"
          - name: OPENCV_LOG_LEVEL
            value: "debug"
          - name: OPENCV_VIDEOIO_DEBUG
            value: "1"
      volumes:
        - name: dev-video0
          hostPath:
            path: /dev/video0
