- name: Start slaves
  hosts: slaves
  become: true
  become_method: sudo
  tasks:
    - name: Check connection to internet
      uri:
        url: "https://google.com"
        return_content: true
        timeout: 3
      register: result
      ignore_errors: true
    - name: Print connection to internet
      ansible.builtin.debug:
        var: result.status

    - name: Pull latest image
      docker_image:
        name: sid220/apriltag_localisation:latest
        source: pull
      when: result.status == 200

    - name: Make project directory
      file:
        path: /lib/apriltag
        state: directory

    - name: Pull latest jcompose file
      get_url:
        url: https://raw.githubusercontent.com/Sid220/docker-apriltag-localisation/master/compose.jyml
        dest: /lib/apriltag/compose.jyml
      when: result.status == 200

    - name: Pull latest pycompose file
      get_url:
        url: https://raw.githubusercontent.com/Sid220/docker-apriltag-localisation/master/compose.py
        dest: /lib/apriltag/compose.py
      when: result.status == 200

    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: /lib/apriltag
        state: absent
      ignore_errors: true

    - name: Startup application
      command:
        cmd: /usr/local/bin/jinja-compose -d /usr/local/bin/docker-compose
        chdir: /lib/apriltag
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output


