- name: Start slaves
  hosts: slaves
  become: true
  become_method: sudo
  tasks:
    - name: Pull latest image
      docker_image:
        name: sid220/apriltag_localisation:latest
    - name: Pull latest compose file
      get_url:
        url: https://raw.githubusercontent.com/sid220/docker-apriltag-localisation/master/compose.yaml
        dest: /home/ubuntu/apriltag/compose.yaml
    - name: Startup application
      community.docker.docker_compose:
        project_src: /home/ubuntu/apriltag
        project_name: apriltag


