name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to docker
      shell: bash
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: docker login --password "$DOCKER_PASS" --username "sid220"
    - name: Create and enter builder
      run: docker buildx create --name apriltag-builder && docker buildx use apriltag-builder
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t sid220/apriltag_localisation:latest -t sid220/apriltag_localisation:$(date +%s) --push .
